name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        derivation:
          - nixosConfigurations.amantha-nixos
          - darwinConfigurations.amantha-air
          - darwinConfigurations.amantha-mbp
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-24.05
    - uses: cachix/cachix-action@v14
      with:
        name: alexymantha
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: amantha-nixos
      run: nix build .#${{ matrix.derivation }}.config.system.build.toplevel
