name: "Build"
on:
  pull_request:
  push:
jobs:
  build-nixos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - amantha-nixos
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-24.05
    - uses: cachix/cachix-action@v14
      with:
        name: alexymantha
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: amantha-nixos
      run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
  
  build-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        host:
          - amantha-mbp
          - amantha-air
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-24.05
    - uses: cachix/cachix-action@v14
      with:
        name: alexymantha
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: mkdir -p /etc/ssl/certs && touch /etc/ssl/certs/all_trusted_certs.pem
    - name: amantha-nixos
      run: nix build .#darwinConfigurations.${{ matrix.host }}.config.system.build.toplevel
